FROM node:latest

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN yarn global add mysql express
RUN yarn global add nodemon

# Bundle app source
COPY . .

EXPOSE 3000

CMD [ "nodemon", "index.js" ]
